[package]
name = "tether-esi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
chrono.workspace = true
eve-esi-client.workspace = true
jsonwebtoken.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tether-db.workspace = true
tokio.workspace = true
tracing.workspace = true
tether-core.workspace = true
tether-net.workspace = true
thiserror.workspace = true
oauth2.workspace = true

[dev-dependencies]
jsonwebtoken = { workspace = true, features = ["use_pem"] }
tokio.workspace = true
wiremock.workspace = true
serde_json.workspace = true
