[package]
name = "tether-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
dev-login = ["tether-web/dev-login"]
dev-docs = ["tether-web/dev-docs"]
# Everything for local development.
dev = ["dev-login", "dev-docs"]

[[bin]]
name = "tether"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
tether-cli.workspace = true
tether-core.workspace = true
tether-db.workspace = true
tether-esi.workspace = true
tether-jobs.workspace = true
tether-web.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
